/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    sports: Sport;
    seasons: Season;
    teams: Team;
    games: Game;
    opponents: Opponent;
    articles: Article;
    tags: Tag;
    links: Link;
    galleries: Gallery;
    'payload-kv': PayloadKv;
    'payload-folders': FolderInterface;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    'payload-folders': {
      documentsAndFolders: 'payload-folders' | 'media';
    };
  };
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    sports: SportsSelect<false> | SportsSelect<true>;
    seasons: SeasonsSelect<false> | SeasonsSelect<true>;
    teams: TeamsSelect<false> | TeamsSelect<true>;
    games: GamesSelect<false> | GamesSelect<true>;
    opponents: OpponentsSelect<false> | OpponentsSelect<true>;
    articles: ArticlesSelect<false> | ArticlesSelect<true>;
    tags: TagsSelect<false> | TagsSelect<true>;
    links: LinksSelect<false> | LinksSelect<true>;
    galleries: GalleriesSelect<false> | GalleriesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-folders': PayloadFoldersSelect<false> | PayloadFoldersSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    navigation: Navigation;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    navigation: NavigationSelect<false> | NavigationSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  caption?: string | null;
  /**
   * Controls which Resources page(s) this shows on — tags are open, use whichever apply.
   */
  tags?: (number | Tag)[] | null;
  /**
   * Display title in Resources listings — distinct from Alt Text above, which is for screen readers.
   */
  title?: string | null;
  description?: string | null;
  sortOrder?: number | null;
  isPublic?: boolean | null;
  folder?: (number | null) | FolderInterface;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags".
 */
export interface Tag {
  id: number;
  name: string;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders".
 */
export interface FolderInterface {
  id: number;
  name: string;
  folder?: (number | null) | FolderInterface;
  documentsAndFolders?: {
    docs?: (
      | {
          relationTo?: 'payload-folders';
          value: number | FolderInterface;
        }
      | {
          relationTo?: 'media';
          value: number | Media;
        }
    )[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sports".
 */
export interface Sport {
  id: number;
  name: string;
  slug: string;
  seasonType: 'Fall' | 'Winter' | 'Spring';
  sortOrder?: number | null;
  /**
   * YouTube video ID (the part after "v=" in the URL) to play muted/looped as this sport's hub-page hero background. Leave blank to fall back to a plain background.
   */
  heroVideoId?: string | null;
  /**
   * Background photo for this sport's tile on the /sports grid. Leave blank to fall back to a plain dark tile.
   */
  coverImage?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seasons".
 */
export interface Season {
  id: number;
  /**
   * e.g. "2025-2026"
   */
  year: string;
  seasonType: 'Fall' | 'Winter' | 'Spring';
  isCurrent?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "teams".
 */
export interface Team {
  id: number;
  sport: number | Sport;
  level: 'Varsity' | 'Junior Varsity' | 'Freshman' | '8th Grade' | '7th Grade' | 'Junior High';
  gender: 'Boys' | 'Girls' | 'Co-Ed';
  schoolLevel: 'High School' | 'Junior High';
  slug: string;
  displayName: string;
  shortName?: string | null;
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "games".
 */
export interface Game {
  id: number;
  team: number | Team;
  season: number | Season;
  /**
   * Upsert key used by the external sync process. Do not edit manually.
   */
  externalEventId?: string | null;
  eventType?: ('Game' | 'Practice' | 'Scrimmage' | 'Other') | null;
  date: string;
  /**
   * Display string, e.g. "07:00 PM"
   */
  time?: string | null;
  /**
   * 24-hour form for sorting, e.g. "19:00"
   */
  time24?: string | null;
  isTimeTBD?: boolean | null;
  homeOrAway?: ('Home' | 'Away' | 'Neutral') | null;
  opponentName?: string | null;
  opponentMascot?: string | null;
  location?: string | null;
  isConferenceGame?: boolean | null;
  isCancelled?: boolean | null;
  isPostponed?: boolean | null;
  /**
   * Editor-owned — the external sync process must never write to this field.
   */
  homeScore?: number | null;
  /**
   * Editor-owned — the external sync process must never write to this field.
   */
  awayScore?: number | null;
  /**
   * Editor-owned — the external sync process must never write to this field.
   */
  result?: ('W' | 'L' | 'T') | null;
  /**
   * Editor-owned — the external sync process must never write to this field.
   */
  notes?: string | null;
  /**
   * Soft-delete marker.
   */
  status?: ('active' | 'removed') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "opponents".
 */
export interface Opponent {
  id: number;
  /**
   * The short name Games store, e.g. "Wickliffe" (not "Wickliffe High School").
   */
  name: string;
  mascot?: string | null;
  /**
   * Other ways this school's name shows up in the EventLink feed, e.g. "Wickliffe HS", "Wickliffe High School". Add one whenever a game doesn't pick up this logo automatically.
   */
  aliases?:
    | {
        alias: string;
        id?: string | null;
      }[]
    | null;
  logo?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: number;
  title: string;
  slug: string;
  excerpt?: string | null;
  /**
   * Article: a normal story with its own page. External Link: clicking the card sends visitors straight to a URL (e.g. a YouTube video, or a page elsewhere on this site). PDF: clicking the card opens an uploaded PDF directly.
   */
  linkType: 'article' | 'external' | 'pdf';
  /**
   * Only used for standard Articles.
   */
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Full URL, e.g. https://youtube.com/watch?v=... or https://example.com/page
   */
  externalUrl?: string | null;
  pdfFile?: (number | null) | Media;
  /**
   * Thumbnail shown on article/news cards — used for every link type, including External Link and PDF.
   */
  heroImage: number | Media;
  relatedTeams?: (number | Team)[] | null;
  relatedSports?: (number | Sport)[] | null;
  /**
   * For content that doesn't fit team/sport scoping, e.g. "Booster Club", "Fundraiser" — or any other tag.
   */
  tags?: (number | Tag)[] | null;
  publishedDate: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "links".
 */
export interface Link {
  id: number;
  title: string;
  linkType: 'external' | 'video';
  /**
   * Full URL, e.g. https://docs.google.com/...
   */
  url?: string | null;
  /**
   * YouTube video ID (the part after "v=") — same convention as Sports.heroVideoId.
   */
  videoId?: string | null;
  /**
   * Tags for filtering and organization — used across the whole site, not just this collection.
   */
  tags?: (number | Tag)[] | null;
  description?: string | null;
  isPublic?: boolean | null;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "galleries".
 */
export interface Gallery {
  id: number;
  title: string;
  /**
   * Looked up by a developer-wired page to render this gallery.
   */
  slug: string;
  description?: string | null;
  isPublic?: boolean | null;
  /**
   * Tag the gallery itself for your own organization — separate from tagging individual items inside it.
   */
  tags?: (number | Tag)[] | null;
  /**
   * Optional groupings, e.g. "Fall Sports". Leave heading blank for one unlabeled group.
   */
  sections?:
    | {
        heading?: string | null;
        items?:
          | {
              /**
               * An uploaded photo/PDF (Media) or a video/external link (Links).
               */
              item:
                | {
                    relationTo: 'media';
                    value: number | Media;
                  }
                | {
                    relationTo: 'links';
                    value: number | Link;
                  };
              caption?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'sports';
        value: number | Sport;
      } | null)
    | ({
        relationTo: 'seasons';
        value: number | Season;
      } | null)
    | ({
        relationTo: 'teams';
        value: number | Team;
      } | null)
    | ({
        relationTo: 'games';
        value: number | Game;
      } | null)
    | ({
        relationTo: 'opponents';
        value: number | Opponent;
      } | null)
    | ({
        relationTo: 'articles';
        value: number | Article;
      } | null)
    | ({
        relationTo: 'tags';
        value: number | Tag;
      } | null)
    | ({
        relationTo: 'links';
        value: number | Link;
      } | null)
    | ({
        relationTo: 'galleries';
        value: number | Gallery;
      } | null)
    | ({
        relationTo: 'payload-folders';
        value: number | FolderInterface;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  tags?: T;
  title?: T;
  description?: T;
  sortOrder?: T;
  isPublic?: T;
  folder?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sports_select".
 */
export interface SportsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  seasonType?: T;
  sortOrder?: T;
  heroVideoId?: T;
  coverImage?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seasons_select".
 */
export interface SeasonsSelect<T extends boolean = true> {
  year?: T;
  seasonType?: T;
  isCurrent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "teams_select".
 */
export interface TeamsSelect<T extends boolean = true> {
  sport?: T;
  level?: T;
  gender?: T;
  schoolLevel?: T;
  slug?: T;
  displayName?: T;
  shortName?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "games_select".
 */
export interface GamesSelect<T extends boolean = true> {
  team?: T;
  season?: T;
  externalEventId?: T;
  eventType?: T;
  date?: T;
  time?: T;
  time24?: T;
  isTimeTBD?: T;
  homeOrAway?: T;
  opponentName?: T;
  opponentMascot?: T;
  location?: T;
  isConferenceGame?: T;
  isCancelled?: T;
  isPostponed?: T;
  homeScore?: T;
  awayScore?: T;
  result?: T;
  notes?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "opponents_select".
 */
export interface OpponentsSelect<T extends boolean = true> {
  name?: T;
  mascot?: T;
  aliases?:
    | T
    | {
        alias?: T;
        id?: T;
      };
  logo?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  linkType?: T;
  body?: T;
  externalUrl?: T;
  pdfFile?: T;
  heroImage?: T;
  relatedTeams?: T;
  relatedSports?: T;
  tags?: T;
  publishedDate?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags_select".
 */
export interface TagsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "links_select".
 */
export interface LinksSelect<T extends boolean = true> {
  title?: T;
  linkType?: T;
  url?: T;
  videoId?: T;
  tags?: T;
  description?: T;
  isPublic?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "galleries_select".
 */
export interface GalleriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  isPublic?: T;
  tags?: T;
  sections?:
    | T
    | {
        heading?: T;
        items?:
          | T
          | {
              item?: T;
              caption?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders_select".
 */
export interface PayloadFoldersSelect<T extends boolean = true> {
  name?: T;
  folder?: T;
  documentsAndFolders?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName?: string | null;
  logo?: (number | null) | Media;
  /**
   * School address shown in the top banner, e.g. "100 Bulldog Ln, Poland, OH 44514".
   */
  address?: string | null;
  /**
   * Hex color, e.g. #123456
   */
  primaryColor?: string | null;
  /**
   * Hex color, e.g. #abcdef
   */
  secondaryColor?: string | null;
  footerText?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * YouTube video ID (the part after "v=" in the URL) to play muted/looped as the home page hero background. Leave blank to fall back to a plain background.
   */
  heroVideoId?: string | null;
  heroHeading?: string | null;
  heroTagline?: string | null;
  socialLinks?:
    | {
        platform?: ('facebook' | 'twitter' | 'instagram' | 'youtube') | null;
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: number;
  links?:
    | {
        label: string;
        url: string;
        showInHeader?: boolean | null;
        showInFooter?: boolean | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  logo?: T;
  address?: T;
  primaryColor?: T;
  secondaryColor?: T;
  footerText?: T;
  heroVideoId?: T;
  heroHeading?: T;
  heroTagline?: T;
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  links?:
    | T
    | {
        label?: T;
        url?: T;
        showInHeader?: T;
        showInFooter?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}